### ISSUE TITLE
Born default time?

### ISSUE THREAD

**Issue by BlackHawk94** [sizzlorox/Idle-RPG-Bot#207]
waiting 3 days to born, there's a timer for pick a new player?

**Comment by sizzlorox** [comment]
> waiting 3 days to born, there's a timer for pick a new player?

This may be a bug from a previous update. I've just patched it Sorry for the inconvenience

**Comment by BlackHawk94** [comment]
After sync the repo
> idle-rpg-bot@0.0.1 start /app
> NODE_ENV=production node app.js
Running Production Env
/app/settings.js:12
botOperators: process.env.DISCORD_BOT_OPERATORS_ID.replace(' ', '').split(','),
TypeError: Cannot read property 'replace' of undefined
at Object.<anonymous> (/app/settings.js:12:54)
at Module._compile (internal/modules/cjs/loader.js:688:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
at Module.load (internal/modules/cjs/loader.js:598:32)
at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
at Function.Module._load (internal/modules/cjs/loader.js:529:3)
at Module.require (internal/modules/cjs/loader.js:636:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object.<anonymous> (/app/idle-rpg/utils/enumHelper.js:1:83)
at Module._compile (internal/modules/cjs/loader.js:688:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! idle-rpg-bot@0.0.1 start: `NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the idle-rpg-bot@0.0.1 start script.
fixed with revert change in settings.js:12

**Comment by sizzlorox** [comment]
> After sync the repo

The .env variable `DISCORD_BOT_OPERATOR_ID` has been changeed to `DISCORD_BOT_OPERATORS_ID`

As now you can have more than one bot operator. The readme has been updated aswell with an example of having more than one bot operator. Sorry I had forgot to mention these updates
